version: '3'
services: 
  nuxt:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - "8080:8080"

    networks:
      - csmsite_network
networks:
  csmsite_network:
    external: true